### ISSUE TITLE
Unable to compile on OS X 10.8.3 

### ISSUE THREAD

**Issue by thorsager** [tomaszmrugalski/dibbler#3]
When trying to compile dibbler (master) on OS X I get the following error

<snip>
lowlevel-bsd.c:332:2: error: #error "Both IPV6_RECVPKTINFO and IPV6_PKTINFO not defined. Need at least one of them"
lowlevel-bsd.c: In function ‘sock_recv’:
lowlevel-bsd.c:463: error: ‘IPV6_PKTINFO’ undeclared (first use in this function)
lowlevel-bsd.c:463: error: (Each undeclared identifier is reported only once
lowlevel-bsd.c:463: error: for each function it appears in.)
make[1]: **\* [libLowLevel_a-lowlevel-bsd.o] Error 1
make: **\* [all-recursive] Error 1
</snip>

however if I manually set HAVE_DECL_IPV6_PKTINFO to 1 and add
# define __APPLE_USE_RFC_229

to Port-bsd/lowlevel-bsd.c the whole ting compiles and runs, no problem (it would seam)

Note it.. I'm very new to OS X and there might be something I'm missing?
